apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: react-front
        image: 728551823587.dkr.ecr.us-east-1.amazonaws.com/front-despacho:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: innovatech
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: front-despacho
