apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ventas-api
        image: 728551823587.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ventas-service
  namespace: innovatech
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: back-ventas
